### ISSUE TITLE
ValueError: Cannot load CLIPTextModel from runwayml/stable-diffusion-v1-5 because the following keys are missing:   text_model.embeddings.position_ids. 

### ISSUE THREAD

**Issue by katie312** [mkshing/svdiff-pytorch#16]
Hello, I ran into this prob by the following steps. I would be appreciate it if someone could help here, THX! 🥹

this is my start script:
```export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export INSTANCE_DIR="xxx"
export CLASS_DIR="xxx"
export OUTPUT_DIR="xxx"

accelerate launch train_svdiff.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="xxx" \
  --class_prompt="xxx" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-3 \
  --learning_rate_1d=1e-6 \
  --train_text_encoder \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=500 \
```

this is what i got

```11/25/2023 15:35:20 - INFO - __main__ - Distributed environment: DistributedType.NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████| 806/806 [00:00<00:00, 2.27MB/s]
Downloading tokenizer/vocab.json: 100%|████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 2.49MB/s]
Downloading tokenizer/merges.txt: 100%|██████████████████████████████████████████| 525k/525k [00:00<00:00, 3.19MB/s]
Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████████| 472/472 [00:00<00:00, 2.36MB/s]
Downloading (…)cheduler_config.json: 100%|█████████████████████████████████████████| 308/308 [00:00<00:00, 1.72MB/s]
{'prediction_type', 'clip_sample_range', 'variance_type'} was not found in config. Values will be initialized to default values.
Downloading (…)_encoder/config.json: 100%|█████████████████████████████████████████| 617/617 [00:00<00:00, 4.07MB/s]
Downloading model.safetensors: 100%|█████████████████████████████████████████████| 492M/492M [02:59<00:00, 2.75MB/s]
Traceback (most recent call last):
  File "/home/katie/svdiff-pytorch/train_svdiff.py", line 1057, in <module>
    main(args)
  File "/home/katie/svdiff-pytorch/train_svdiff.py", line 703, in main
    text_encoder = load_text_encoder_for_svdiff(args.pretrained_model_name_or_path, subfolder="text_encoder", revision=args.revision)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie/svdiff-pytorch/svdiff_pytorch/utils.py", line 106, in load_text_encoder_for_svdiff
    raise ValueError(
ValueError: Cannot load CLIPTextModel from runwayml/stable-diffusion-v1-5 because the following keys are missing: 
 text_model.embeddings.position_ids. 
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomely initialize those weights or else make sure your checkpoint file is correct.
Traceback (most recent call last):
  File "/home/katie/miniconda3/envs/sv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/katie/miniconda3/envs/sv/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/katie/miniconda3/envs/sv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/home/katie/miniconda3/envs/sv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/katie/miniconda3/envs/sv/bin/python', 'train_svdiff.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--instance_data_dir=/home/katie/svdiff-pytorch/INS_isic', '--class_data_dir=class_isic', '--output_dir=svdiff-isic-out-model', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=A picture of a sks skin lesion with Melanomic Neves', '--class_prompt=A picture of a skin lesion with Melanomic Neves', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=1e-3', '--learning_rate_1d=1e-6', '--train_text_encoder', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--max_train_steps=500']' returned non-zero exit status 1.
```

I did set up my env by `$ pip install svdiff-pytorch `

**Comment by jingyu1128** [comment]
请问解决了吗

**Comment by hecoding** [comment]
Hi, the code is just old. You can either
1. install the package versions specified in `requirements.txt` and run the code normally. Or
2. edit `svdiff_pytorch/utils.py` and right below L104 add
```python
if "text_model.embeddings.position_ids" in missing_keys:
    missing_keys.remove("text_model.embeddings.position_ids")
```

The second option is dirtier and will only work as long as new diffusers versions don't introduce breaking changes with v0.14.
